### ISSUE TITLE
Certain countries and states are not getting filled in Starting_National_tags.png

### ISSUE THREAD

**Issue by Araxiel** [Licarious/Vic3MapCSharp#5]
I wanted to get a 1.5.12 vanilla map and copied over the relevant vanilla files, and while nearly all of it works fine, the `Starting_National_tags.png` and `Starting_National.png` map is missing a bunch of states that are just empty/transparent.
![Starting_National_tags](https://github.com/Licarious/Vic3MapCSharp/assets/11295969/de9cd767-7b72-432a-941f-442d569b5c21)

And it's only those two maps that don't output correctly. In comparison, `State_Map_Names.png` working fine.
![State_Map_Names](https://github.com/Licarious/Vic3MapCSharp/assets/11295969/1b165088-ef96-4774-9df3-3ff989e58dec)

While typing this out and further looking at it, I wonder how much of this might be related to the DLCs, since France and Algeria are missing (Something Voice of the People DLC slightly changes) and parts of Latin America (nations which Colossus of the South edits).

I can't find any error log or similar to upload.

**Comment by Licarious** [comment]
Quotations around provIDs in the history/states files were the issue.  That has been fixed  in the main branch for a while now.  I have now pushed that into release V1.3.1.

**Comment by Licarious** [comment]
Quotations around provIDs in the history/states files were the issue. That has been fixed in the main branch for a while now. I have now pushed that into release V1.3.1.

**Comment by Araxiel** [comment]
Since this is closed, I do wanna just add, this is a extremely useful tool for my project of working on an alt-history conversion. Especially the splitting up of files, like dedicated province border or state border files.
