### ISSUE TITLE
There is some error with the version1.6 update

### ISSUE THREAD

**Issue by LI-MOFEI** [Licarious/Vic3MapCSharp#6]
![屏幕截图 2024-03-07 124834](https://github.com/Licarious/Vic3MapCSharp/assets/107630562/44c89151-fc81-426d-9fd4-faa1460c2715)

**Comment by LI-MOFEI** [comment]
Maybe for a change in the file default.map
![Uploading 屏幕截图 2024-03-07 130435.jpg…]()

**Comment by CathayZhao** [comment]
I meet the same problem.

**Comment by Licarious** [comment]
looks like there was a tab between 2 of those IDs in default.map.  I pushed an update that changed the splitting to be general white space. 
Let me know if this fixes it for you guys.

**Comment by CathayZhao** [comment]
Works great now, thanks!
